/**
 * DO NOT RUN THIS SCRIPT AS-IS. See create-network-pro.js's header for the
 * full explanation — same situation here: the real course id is
 * "binary-cloud-fundamentals" (not "binary-cloud"), a live check on
 * 2026-08-29 found it already has 20 modules of real content, and this
 * script's module ids ("module-1".."module-7") were guessed, not verified
 * against the real structure. Do not run until that's checked against
 * Firestore directly.
 */

const admin = require("firebase-admin");
admin.initializeApp({ credential: admin.credential.applicationDefault() });

const db = admin.firestore();
const COURSE_ID = "binary-cloud-fundamentals";

async function addFlashcards(moduleId, cards) {
  const col = db.collection("courses").doc(COURSE_ID).collection("modules").doc(moduleId).collection("flashcards");
  for (let i = 0; i < cards.length; i++) await col.doc(`card-${i + 1}`).set(cards[i]);
}

async function addQuiz(moduleId, questions) {
  const col = db.collection("courses").doc(COURSE_ID).collection("modules").doc(moduleId).collection("quiz");
  for (let i = 0; i < questions.length; i++) await col.doc(`q-${i + 1}`).set(questions[i]);
}

async function createModule(moduleId, title, order, status, flashcards, quiz) {
  const ref = db.collection("courses").doc(COURSE_ID).collection("modules").doc(moduleId);
  const existing = await ref.get();
  if (existing.exists && existing.data().title) {
    console.log(`SKIPPED ${COURSE_ID}/${moduleId} — a module with title "${existing.data().title}" already exists there.`);
    return;
  }
  await ref.set({
    title,
    subtitle: `${flashcards.length} flashcards · ${quiz.length} questions`,
    order,
    status,
  });
  await addFlashcards(moduleId, flashcards);
  await addQuiz(moduleId, quiz);
  console.log(`${COURSE_ID}/${moduleId} ("${title}"): ${flashcards.length} flashcards, ${quiz.length} quiz questions`);
}

async function main() {
  // ── MODULE 1 — Introduction to Cloud Computing ────────────────────────────
  await createModule("module-1", "Introduction to Cloud Computing", 1, "active",
    [
      { order: 1, question: "What is cloud computing?", answer: "Cloud computing is the on-demand delivery of computing resources — servers, storage, databases, networking, software — over the internet, with the customer paying for what they use rather than owning and maintaining physical infrastructure themselves.", example: "Instead of buying and maintaining a physical server, a startup rents virtual servers from a cloud provider, scaling capacity up or down as needed." },
      { order: 2, question: "What is the difference between on-premises and cloud infrastructure?", answer: "On-premises infrastructure is physically owned, housed, and maintained by the organisation itself. Cloud infrastructure is owned and maintained by a third-party provider, accessed remotely, with the customer typically paying based on usage rather than large upfront capital costs.", example: "A company running its own data centre with owned servers is on-premises; the same company renting virtual machines from a cloud provider is using cloud infrastructure." },
      { order: 3, question: "What is \"on-demand self-service\" as an essential characteristic of cloud computing?", answer: "On-demand self-service means a customer can provision computing resources — like server capacity — automatically, without needing to contact the provider's staff or wait for manual approval each time.", example: "Spinning up a new virtual server through a web console or API in minutes, without a phone call to the provider, is on-demand self-service." },
      { order: 4, question: "What is \"rapid elasticity\" in cloud computing?", answer: "Rapid elasticity is the ability to scale resources up or down quickly to match demand, often automatically, so capacity can expand during high demand and shrink again once it passes — customers pay only for what's actually needed at any given time.", example: "An e-commerce site automatically adding more server capacity during a holiday sale, then scaling back down afterward, demonstrates rapid elasticity." },
      { order: 5, question: "What is \"resource pooling\" in cloud computing?", answer: "Resource pooling means a cloud provider's physical and virtual resources are shared across multiple customers using a multi-tenant model, with resources dynamically assigned and reassigned based on demand, while customers generally have no control over or knowledge of the exact physical location of their resources.", example: "Many different customers' virtual machines may run on the same underlying physical hardware, isolated from each other but sharing the pooled infrastructure." },
      { order: 6, question: "What does \"measured service\" mean in cloud computing?", answer: "Measured service means resource usage is automatically monitored, controlled, and reported, providing transparency for both provider and customer — typically forming the basis for pay-as-you-go billing.", example: "A cloud bill itemising exact compute hours, storage used, and data transferred reflects measured service." },
      { order: 7, question: "What is the difference between CapEx and OpEx, and how does cloud shift this balance?", answer: "CapEx (capital expenditure) is large upfront investment in owned assets, like buying servers outright. OpEx (operational expenditure) is ongoing, usage-based spending. Cloud computing typically shifts IT costs from CapEx toward OpEx, since you rent capacity rather than buy hardware.", example: "Buying a $50,000 server outright is CapEx; paying a monthly cloud bill based on actual usage is OpEx." },
      { order: 8, question: "What is a data centre region, and why do cloud providers offer multiple regions?", answer: "A region is a specific geographic location where a cloud provider operates data centres. Multiple regions let customers place resources closer to their users for lower latency, meet data residency/legal requirements, and improve resilience by spreading resources across locations.", example: "A company with mostly European customers might choose a European region to reduce latency and comply with local data residency expectations." },
      { order: 9, question: "What is an availability zone?", answer: "An availability zone is an isolated location within a region — typically a separate physical data centre with independent power, cooling, and networking — allowing resources to be spread across zones so a failure in one doesn't take down everything.", example: "Running redundant copies of an application across two availability zones means one data centre's power outage doesn't take the whole application offline." },
      { order: 10, question: "What is vendor lock-in, and why is it a consideration in cloud strategy?", answer: "Vendor lock-in is the difficulty and cost of switching cloud providers once an organisation has built deeply around one provider's specific, non-standard services and tools — a real trade-off against the convenience of using a provider's most integrated offerings.", example: "Building an application entirely around one provider's proprietary database service can make migrating to another provider later expensive and technically complex." },
      { order: 11, question: "What is the shared responsibility model, at a high level?", answer: "The shared responsibility model divides security and operational responsibility between the cloud provider and the customer — the provider is generally responsible for the security of the underlying infrastructure, while the customer is responsible for securing what they build and configure on top of it.", example: "A provider secures the physical data centre and host hardware; the customer is still responsible for configuring their own firewall rules and access permissions correctly." },
      { order: 12, question: "Why might an organisation choose cloud computing over traditional infrastructure?", answer: "Common reasons include avoiding large upfront hardware costs, faster provisioning of resources, easier scaling to match demand, reduced need for in-house infrastructure maintenance, and access to a provider's global infrastructure without building it yourself.", example: "A startup launching quickly with no capital for its own data centre can be running production infrastructure within hours using a cloud provider." },
    ],
    [
      { order: 1, question: "What is cloud computing?", options: ["A type of physical hardware", "The on-demand delivery of computing resources over the internet, paid for based on usage", "A programming language", "A local network protocol"], correctIndex: 1, explanation: "Cloud computing delivers resources like compute, storage, and networking over the internet on a usage basis." },
      { order: 2, question: "What is a key difference between on-premises and cloud infrastructure?", options: ["On-premises is always cheaper", "On-premises is owned and maintained by the organisation; cloud is provided by a third party", "Cloud infrastructure cannot be scaled", "There is no real difference"], correctIndex: 1, explanation: "On-premises infrastructure is self-owned and self-maintained; cloud infrastructure is provided and maintained by a third party." },
      { order: 3, question: "What does \"on-demand self-service\" mean in cloud computing?", options: ["Resources require manual provider approval every time", "Customers can provision resources automatically without contacting provider staff", "Only the provider can request new resources", "It refers to customer support chat availability"], correctIndex: 1, explanation: "On-demand self-service lets customers provision resources themselves, without needing manual provider intervention." },
      { order: 4, question: "What does \"rapid elasticity\" allow a cloud customer to do?", options: ["Permanently fix resource capacity", "Scale resources up or down quickly to match demand", "Avoid paying for any resources", "Guarantee zero downtime"], correctIndex: 1, explanation: "Rapid elasticity allows capacity to expand or shrink quickly as demand changes." },
      { order: 5, question: "What does resource pooling describe?", options: ["Each customer gets entirely separate physical hardware", "Shared infrastructure dynamically allocated across multiple customers", "A backup strategy", "A pricing discount"], correctIndex: 1, explanation: "Resource pooling means infrastructure is shared across customers in a multi-tenant model, dynamically assigned as needed." },
      { order: 6, question: "What does \"measured service\" enable?", options: ["Unlimited free usage", "Usage-based billing through automatic monitoring and reporting", "Manual invoicing only", "A fixed monthly fee regardless of usage"], correctIndex: 1, explanation: "Measured service tracks actual usage, forming the basis for pay-as-you-go billing." },
      { order: 7, question: "How does cloud computing typically shift IT spending?", options: ["From OpEx toward CapEx", "From CapEx toward OpEx", "It eliminates all IT spending", "It has no effect on spending patterns"], correctIndex: 1, explanation: "Cloud computing shifts costs from large upfront capital investment (CapEx) toward ongoing, usage-based spending (OpEx)." },
      { order: 8, question: "Why might an organisation choose a cloud region close to its users?", options: ["To increase costs deliberately", "To reduce latency and potentially meet data residency requirements", "Region choice has no practical effect", "Because all regions have identical pricing regardless of location"], correctIndex: 1, explanation: "Choosing a nearby region reduces latency for users and can help meet local data residency expectations." },
      { order: 9, question: "What is an availability zone?", options: ["A pricing tier", "An isolated data centre location within a region, used for resilience", "A type of virtual machine", "A customer support region"], correctIndex: 1, explanation: "Availability zones are isolated locations within a region, letting resources be spread out for resilience against localised failures." },
      { order: 10, question: "What is vendor lock-in?", options: ["A security feature preventing unauthorised access", "The difficulty and cost of switching providers after building deeply around one provider's services", "A type of encryption", "A backup strategy"], correctIndex: 1, explanation: "Vendor lock-in describes the switching cost created by deep reliance on one provider's specific, non-standard services." },
      { order: 11, question: "Under the shared responsibility model, who is generally responsible for securing the underlying physical infrastructure?", options: ["The customer", "The cloud provider", "Neither party", "A third-party auditor"], correctIndex: 1, explanation: "The provider typically secures the underlying infrastructure, while the customer secures what they configure on top of it." },
      { order: 12, question: "Which of these is a common reason organisations choose cloud computing?", options: ["To increase upfront hardware costs", "Faster provisioning and easier scaling to match demand", "To eliminate the need for any security controls", "To avoid ever paying for infrastructure"], correctIndex: 1, explanation: "Faster provisioning and flexible scaling are commonly cited advantages of cloud computing over traditional infrastructure." },
    ]
  );

  // ── MODULE 2 — Service Models ─────────────────────────────────────────────
  await createModule("module-2", "Service Models", 2, "locked",
    [
      { order: 1, question: "What is IaaS (Infrastructure as a Service)?", answer: "IaaS provides fundamental computing resources — virtual machines, storage, and networking — over the internet, with the customer managing the operating system, applications, and configuration on top of provider-managed hardware.", example: "Renting a virtual server where you install and manage your own operating system and software is IaaS." },
      { order: 2, question: "What is PaaS (Platform as a Service)?", answer: "PaaS provides a managed platform for developing, running, and managing applications without needing to manage the underlying servers, operating systems, or infrastructure — the provider handles more of the stack than with IaaS.", example: "Deploying an application to a platform that automatically handles server provisioning, scaling, and OS patching is using PaaS." },
      { order: 3, question: "What is SaaS (Software as a Service)?", answer: "SaaS delivers a complete, ready-to-use software application over the internet, with the provider managing everything from infrastructure to the application itself — the customer just uses the software, typically through a browser.", example: "Using a web-based email or project management tool that requires no installation or server management is SaaS." },
      { order: 4, question: "How does responsibility shift across IaaS, PaaS, and SaaS?", answer: "Moving from IaaS to PaaS to SaaS, the provider takes on increasingly more of the management burden, and the customer retains less direct control but also less operational responsibility — IaaS gives the most control and responsibility to the customer; SaaS gives the least.", example: "With IaaS you patch your own OS; with PaaS the platform handles OS patching for you; with SaaS you don't even think about servers at all." },
      { order: 5, question: "What is an example of choosing IaaS over PaaS, and why might a team make that choice?", answer: "A team needing fine-grained control over the operating system, custom software stacks, or specific configurations not supported by a managed platform might choose IaaS, accepting more operational responsibility in exchange for more flexibility.", example: "A team running a highly customised, legacy application with unusual dependencies might need IaaS's flexibility rather than a more restrictive PaaS environment." },
      { order: 6, question: "What is serverless computing, and how does it relate to PaaS?", answer: "Serverless computing is a further evolution where the provider manages practically all infrastructure, automatically allocating resources only when code actually runs — the customer writes and deploys functions without provisioning or managing servers at all, even implicitly.", example: "A function that runs briefly only when triggered by an event, without any server sitting idle waiting for requests, is a serverless model." },
      { order: 7, question: "What is a Database as a Service (DBaaS)?", answer: "DBaaS is a managed database offering, typically considered a form of PaaS, where the provider handles database installation, patching, backups, and scaling, letting customers focus on using the database rather than administering it.", example: "Using a managed database service that automatically handles backups and patching, rather than manually administering database software on a server, is DBaaS." },
      { order: 8, question: "What trade-off exists between control and management overhead across the service models?", answer: "More control (as in IaaS) comes with more management overhead — the customer must handle patching, scaling, and configuration themselves. Less control (as in SaaS) comes with less overhead, since the provider handles nearly everything, but also less flexibility to customise.", example: "A team wanting complete control over their exact software stack accepts more maintenance work than a team happy to use an off-the-shelf SaaS tool." },
      { order: 9, question: "Can an organisation use more than one service model at once?", answer: "Yes — most organisations mix service models depending on the workload, using IaaS for custom applications needing full control, PaaS for standard application development, and SaaS for common business functions like email or CRM.", example: "A company might run its custom application on IaaS, its internal developer tools on PaaS, and use a SaaS product for HR management, all simultaneously." },
      { order: 10, question: "What is Function as a Service (FaaS)?", answer: "FaaS is a specific type of serverless computing where individual functions are deployed and run in response to events, automatically scaling and billing only for the compute time actually consumed while the function executes.", example: "A function that resizes an uploaded image automatically whenever a new file is uploaded, running only during that brief processing time, is FaaS." },
      { order: 11, question: "What is a common misconception about \"serverless\" computing?", answer: "Despite the name, serverless computing still runs on physical servers — the term refers to the customer no longer needing to provision or manage those servers themselves, not to the actual absence of servers.", example: "Believing \"serverless\" means there's literally no server involved is a common misconception — the provider still manages real infrastructure behind the scenes." },
      { order: 12, question: "How do service models relate to the shared responsibility model?", answer: "The service model chosen shifts exactly where the responsibility boundary sits — IaaS leaves the customer responsible for more of the stack (OS, runtime, application), while SaaS shifts nearly everything except data and access management to the provider.", example: "With SaaS, the customer is mainly responsible for managing who has access and what data they put in — the provider handles virtually everything else." },
    ],
    [
      { order: 1, question: "What does IaaS provide?", options: ["A complete, ready-to-use application", "Fundamental computing resources like virtual machines, storage, and networking", "Only a code deployment platform", "Customer support services"], correctIndex: 1, explanation: "IaaS provides raw infrastructure resources, with the customer managing the OS and applications on top." },
      { order: 2, question: "What does PaaS manage that IaaS typically leaves to the customer?", options: ["Nothing — they are identical", "The underlying servers, OS, and infrastructure needed to run applications", "Only the billing system", "The customer's own data"], correctIndex: 1, explanation: "PaaS manages the underlying infrastructure and OS, letting the customer focus on application development." },
      { order: 3, question: "What best describes SaaS?", options: ["Raw virtual machines the customer configures", "A complete, ready-to-use software application delivered over the internet", "A database management tool only", "A networking protocol"], correctIndex: 1, explanation: "SaaS delivers a fully managed, ready-to-use application, typically accessed via a browser." },
      { order: 4, question: "As you move from IaaS to PaaS to SaaS, what generally happens to customer control and provider responsibility?", options: ["Customer control increases and provider responsibility decreases", "Customer control decreases as provider responsibility increases", "Both stay exactly the same across all three", "Only SaaS involves any provider responsibility"], correctIndex: 1, explanation: "Moving toward SaaS, the provider takes on more responsibility while the customer retains less direct control." },
      { order: 5, question: "Why might a team choose IaaS over a more managed option?", options: ["It always requires less effort", "It offers more control and flexibility for custom or unusual configurations", "It is the only option that allows scaling", "IaaS never requires any maintenance"], correctIndex: 1, explanation: "IaaS offers maximum flexibility, useful when a workload needs configuration a managed platform doesn't support." },
      { order: 6, question: "What characterises serverless computing?", options: ["The complete physical absence of servers", "Automatic resource allocation only when code runs, with no server management by the customer", "A requirement to manually provision servers", "It is identical to traditional IaaS"], correctIndex: 1, explanation: "Serverless still uses real servers, but the customer never provisions or manages them directly." },
      { order: 7, question: "What is DBaaS generally considered a form of?", options: ["IaaS", "PaaS", "SaaS only", "A separate, unrelated category"], correctIndex: 1, explanation: "Managed database services are typically categorised as a form of PaaS, since the provider manages the platform beneath the customer's data." },
      { order: 8, question: "What trade-off exists between IaaS and SaaS?", options: ["There is no meaningful trade-off", "IaaS offers more control with more management overhead; SaaS offers less control with less overhead", "SaaS always offers more control than IaaS", "IaaS never requires any customer effort"], correctIndex: 1, explanation: "More control generally comes with more management responsibility, and vice versa." },
      { order: 9, question: "Can an organisation use IaaS, PaaS, and SaaS simultaneously?", options: ["No, only one model can be used at a time", "Yes, most organisations mix models depending on the workload", "Only large enterprises are permitted to mix models", "Mixing models is against best practice"], correctIndex: 1, explanation: "Organisations commonly mix service models to match different workloads' needs." },
      { order: 10, question: "What is FaaS?", options: ["A pricing model for storage", "A serverless model where individual functions run in response to events", "A type of firewall", "A database backup strategy"], correctIndex: 1, explanation: "FaaS runs individual functions triggered by events, billed only for actual execution time." },
      { order: 11, question: "What is a common misconception about \"serverless\" computing?", options: ["That it is more expensive than IaaS", "That there are literally no servers involved at all", "That it cannot scale automatically", "That it requires manual patching"], correctIndex: 1, explanation: "Serverless still runs on real servers — the term refers to the customer not managing them directly." },
      { order: 12, question: "How does choice of service model affect the shared responsibility boundary?", options: ["It has no effect on responsibility", "It shifts exactly how much of the stack the customer versus provider is responsible for", "Only SaaS has any shared responsibility at all", "IaaS removes all customer responsibility"], correctIndex: 1, explanation: "The service model chosen determines where the line falls between customer and provider responsibility." },
    ]
  );

  // ── MODULE 3 — Deployment Models ──────────────────────────────────────────
  await createModule("module-3", "Deployment Models", 3, "locked",
    [
      { order: 1, question: "What is a public cloud?", answer: "A public cloud is infrastructure owned and operated by a third-party provider, with resources shared across multiple customers (multi-tenant) and made available over the public internet, typically on a pay-as-you-go basis.", example: "Renting virtual servers from a major cloud provider that also serves thousands of other customers is using a public cloud." },
      { order: 2, question: "What is a private cloud?", answer: "A private cloud is infrastructure dedicated entirely to one organisation, whether hosted on-premises or by a third party exclusively for that organisation — offering more control and isolation than a public cloud, typically at higher cost.", example: "A bank running its own dedicated cloud-like infrastructure, not shared with any other organisation, due to strict regulatory requirements, is using a private cloud." },
      { order: 3, question: "What is a hybrid cloud?", answer: "A hybrid cloud combines public and private cloud (or on-premises) infrastructure, with workloads and data able to move between environments as needed, giving organisations flexibility to place workloads where they make the most sense.", example: "A company keeps sensitive customer data on a private cloud but runs its public-facing website on a public cloud, connecting the two together." },
      { order: 4, question: "What is a multi-cloud strategy?", answer: "Multi-cloud means using services from more than one public cloud provider simultaneously, often to avoid vendor lock-in, take advantage of different providers' strengths, or meet redundancy and resilience goals.", example: "A company running its main workload on one provider while using a second provider specifically for its data analytics services is practicing multi-cloud." },
      { order: 5, question: "What is a key advantage of public cloud over private cloud?", answer: "Public cloud typically offers lower upfront costs, faster provisioning, and access to a vast range of managed services and global infrastructure without the organisation needing to build and maintain any of it themselves.", example: "A startup can be running globally distributed infrastructure within hours on public cloud, without ever owning a single physical server." },
      { order: 6, question: "What is a key advantage of private cloud over public cloud?", answer: "Private cloud offers greater control, customisation, and isolation — useful for organisations with strict regulatory, security, or performance requirements that a shared, multi-tenant public cloud environment might not adequately satisfy.", example: "A government agency handling classified information might require the isolation a private cloud provides, even at higher cost and complexity." },
      { order: 7, question: "What challenges commonly arise with a hybrid cloud approach?", answer: "Hybrid cloud can introduce added complexity in networking, security consistency, and data synchronisation between environments, requiring careful architecture to make the different environments work together reliably and securely.", example: "Ensuring consistent security policies apply whether a workload runs on-premises or in the public cloud portion of a hybrid setup requires deliberate design effort." },
      { order: 8, question: "What challenges commonly arise with a multi-cloud approach?", answer: "Multi-cloud can increase operational complexity, since teams must manage different providers' tools, APIs, and pricing models, and it can be harder to maintain consistent security and monitoring practices across genuinely different platforms.", example: "A team skilled in one provider's tools may need significant additional training to operate effectively on a second, different provider simultaneously." },
      { order: 9, question: "What is a community cloud?", answer: "A community cloud is shared infrastructure used by several organisations with common concerns — such as compliance requirements or industry needs — offering some of private cloud's benefits while sharing the cost across the community of users.", example: "Several government agencies within one country sharing dedicated cloud infrastructure built to meet a common set of regulatory requirements is a community cloud model." },
      { order: 10, question: "How should an organisation typically decide between deployment models?", answer: "The decision usually weighs cost, required control, regulatory or compliance needs, existing infrastructure investment, and the specific workload's requirements — there's rarely a single \"correct\" answer, and many organisations end up using a mix.", example: "An organisation might use public cloud for its flexible customer-facing app but keep certain regulated financial data on a private or hybrid setup." },
      { order: 11, question: "What is data sovereignty, and how does it influence deployment model choice?", answer: "Data sovereignty refers to legal requirements that certain data must be stored and processed within specific geographic or jurisdictional boundaries, which can influence whether public cloud regions are suitable or whether a private/hybrid approach is needed to maintain compliance.", example: "A country requiring citizens' health data to stay within national borders might push an organisation toward a private cloud or a public cloud region physically located in that country." },
      { order: 12, question: "Is a hybrid cloud the same as a multi-cloud strategy?", answer: "No — hybrid cloud specifically combines private/on-premises infrastructure with public cloud, while multi-cloud specifically means using multiple public cloud providers. An organisation could technically do both at once, but the terms describe different combinations.", example: "A company using one public cloud provider alongside its own private data centre is hybrid; using two different public cloud providers together (with no private infrastructure) is multi-cloud, not hybrid." },
    ],
    [
      { order: 1, question: "What characterises a public cloud?", options: ["Infrastructure dedicated to a single organisation", "Shared, multi-tenant infrastructure owned by a third-party provider", "Infrastructure that never connects to the internet", "A cloud used only by government agencies"], correctIndex: 1, explanation: "Public cloud is multi-tenant infrastructure operated by a provider and shared across many customers." },
      { order: 2, question: "What characterises a private cloud?", options: ["Resources shared across many unrelated customers", "Infrastructure dedicated entirely to one organisation", "A cloud with no security controls", "A free tier of a public cloud"], correctIndex: 1, explanation: "Private cloud is dedicated to a single organisation, offering more control and isolation." },
      { order: 3, question: "What defines a hybrid cloud?", options: ["Using two public cloud providers only", "Combining public and private (or on-premises) infrastructure together", "A cloud used only for testing", "A single-tenant public cloud"], correctIndex: 1, explanation: "Hybrid cloud connects public and private/on-premises environments, allowing workloads to move between them." },
      { order: 4, question: "What is a multi-cloud strategy?", options: ["Combining public and private infrastructure", "Using services from more than one public cloud provider", "Running only on-premises infrastructure", "A backup strategy for a single provider"], correctIndex: 1, explanation: "Multi-cloud specifically means using multiple public cloud providers simultaneously." },
      { order: 5, question: "What is a common advantage of public cloud over private cloud?", options: ["Complete infrastructure isolation", "Lower upfront costs and faster provisioning", "Guaranteed regulatory compliance for any industry", "No need for any security configuration"], correctIndex: 1, explanation: "Public cloud generally offers lower upfront costs and much faster provisioning than building a private cloud." },
      { order: 6, question: "Why might an organisation choose private cloud despite the higher cost?", options: ["It is always cheaper long-term", "Greater control, customisation, and isolation for strict regulatory or security needs", "It requires no maintenance", "It is the only option that supports scaling"], correctIndex: 1, explanation: "Private cloud suits organisations needing tighter control that a shared public environment may not satisfy." },
      { order: 7, question: "What is a common challenge with hybrid cloud architectures?", options: ["They are always simpler than a single environment", "Maintaining consistent networking and security across environments", "They cannot connect to the public internet", "They eliminate the need for any cloud expertise"], correctIndex: 1, explanation: "Hybrid setups require careful design to keep networking and security consistent across different environments." },
      { order: 8, question: "What is a common challenge with a multi-cloud strategy?", options: ["It removes the need for any staff training", "Increased operational complexity managing different providers' tools and APIs", "It always reduces total cost", "It eliminates vendor lock-in concerns entirely"], correctIndex: 1, explanation: "Operating across genuinely different providers adds complexity in tooling, APIs, and consistent practices." },
      { order: 9, question: "What is a community cloud?", options: ["A free public cloud tier", "Shared infrastructure used by organisations with common needs, like compliance requirements", "A private cloud with no shared cost", "A backup deployment model"], correctIndex: 1, explanation: "Community cloud is shared among organisations with common needs, splitting cost while offering some private-cloud benefits." },
      { order: 10, question: "What typically drives the choice between deployment models?", options: ["Only the size of the IT team", "Cost, required control, regulatory needs, and workload requirements together", "A single universal best answer for all organisations", "The programming language used"], correctIndex: 1, explanation: "The decision usually weighs several factors together rather than following one universal rule." },
      { order: 11, question: "What is data sovereignty?", options: ["A pricing model", "Legal requirements that data be stored/processed within specific jurisdictions", "A type of encryption", "A cloud provider's uptime guarantee"], correctIndex: 1, explanation: "Data sovereignty concerns legal jurisdiction requirements over where data physically resides or is processed." },
      { order: 12, question: "Is multi-cloud the same as hybrid cloud?", options: ["Yes, they are always identical", "No — hybrid combines public and private/on-premises; multi-cloud uses multiple public providers", "Multi-cloud always includes a private component", "Hybrid cloud never involves a public cloud provider"], correctIndex: 1, explanation: "The two terms describe different combinations — hybrid mixes public with private/on-prem; multi-cloud uses multiple public providers." },
    ]
  );

  // ── MODULE 4 — Virtualization ─────────────────────────────────────────────
  await createModule("module-4", "Virtualization", 4, "locked",
    [
      { order: 1, question: "What is virtualization?", answer: "Virtualization creates a software-based, virtual version of a physical resource — such as a server, storage device, or network — allowing multiple isolated virtual instances to run on shared physical hardware.", example: "Running several separate virtual servers, each behaving like an independent machine, on one physical server is virtualization in action." },
      { order: 2, question: "What is a hypervisor?", answer: "A hypervisor is software that creates and manages virtual machines, allocating physical hardware resources (CPU, memory, storage) to each virtual machine while keeping them isolated from one another.", example: "A hypervisor running on a physical server allocates portions of its CPU and memory to each of the several virtual machines running on top of it." },
      { order: 3, question: "What is the difference between a Type 1 and Type 2 hypervisor?", answer: "A Type 1 hypervisor runs directly on the physical hardware (\"bare metal\"), typically used in data centres for better performance and efficiency. A Type 2 hypervisor runs on top of an existing operating system, more common for personal or development use.", example: "Enterprise cloud data centres typically use Type 1 hypervisors; running a virtual machine for testing on your personal laptop's existing OS usually uses a Type 2 hypervisor." },
      { order: 4, question: "What is a virtual machine (VM)?", answer: "A virtual machine is a software emulation of a complete physical computer, including its own operating system, running on top of a hypervisor and isolated from other VMs sharing the same physical hardware.", example: "Running Linux and Windows VMs side by side on the same physical machine, each behaving as if it has its own dedicated hardware, uses virtual machines." },
      { order: 5, question: "What are the main benefits of virtualization?", answer: "Virtualization improves hardware utilisation by running multiple workloads on shared physical resources, enables faster provisioning of new environments, supports easier backup and recovery through snapshots, and provides isolation between different workloads.", example: "Instead of one physical server sitting mostly idle running one application, virtualization lets several applications share that same hardware efficiently." },
      { order: 6, question: "What is the difference between a virtual machine and a container?", answer: "A VM virtualizes an entire computer, including a full guest operating system. A container virtualizes at the operating system level, sharing the host OS kernel while isolating the application and its dependencies — making containers much lighter weight and faster to start than VMs.", example: "A VM might take a minute or more to boot a full OS; a container can typically start in a fraction of a second since it doesn't boot a separate OS." },
      { order: 7, question: "Why are containers generally more efficient than virtual machines?", answer: "Because containers share the host operating system's kernel rather than running a full separate OS per instance, they use far less memory and disk space, start much faster, and allow many more instances to run on the same hardware compared to VMs.", example: "A server that might run a handful of full VMs could potentially run dozens or hundreds of lightweight containers using the same hardware resources." },
      { order: 8, question: "What is a VM snapshot?", answer: "A snapshot captures the exact state of a virtual machine at a specific point in time — including its disk, memory, and configuration — allowing it to be restored to that exact state later if needed.", example: "Taking a snapshot before applying a risky software update lets you instantly roll back if the update causes problems." },
      { order: 9, question: "What is VM migration, and why is it useful?", answer: "VM migration moves a running or stopped virtual machine from one physical host to another, often without noticeable downtime (\"live migration\"), useful for load balancing across hardware, performing hardware maintenance, or handling a failing host.", example: "Live-migrating a VM off a physical server that needs maintenance, without the application inside the VM ever going offline, keeps the workload running seamlessly." },
      { order: 10, question: "What is resource overcommitment in virtualization, and what risk does it carry?", answer: "Overcommitment allocates more virtual resources across VMs than physically exist, betting that not every VM will need its full allocation simultaneously — efficient when it works, but it risks performance problems or failures if demand from multiple VMs spikes at the same time.", example: "A host might allocate 32GB of virtual memory across VMs on a machine with only 24GB of physical RAM, relying on not all VMs maxing out memory usage at once." },
      { order: 11, question: "What is a virtual network in the context of virtualization?", answer: "A virtual network is a software-defined network that connects virtual machines or containers, replicating networking functions like switching and routing in software rather than relying solely on physical network hardware.", example: "Virtual machines on the same physical host can communicate over a virtual network switch that exists entirely in software, without needing a physical cable between them." },
      { order: 12, question: "Why does virtualization matter as a foundation for cloud computing?", answer: "Virtualization is the technology that makes efficient, flexible, multi-tenant cloud infrastructure possible — it's what allows a cloud provider to safely run many different customers' isolated workloads on the same shared physical hardware.", example: "The rapid, on-demand provisioning that defines cloud computing relies heavily on the ability to quickly spin up isolated virtual machines on existing hardware, rather than deploying new physical servers for every customer." },
    ],
    [
      { order: 1, question: "What does virtualization create?", options: ["A new physical server", "A software-based, virtual version of a physical resource", "A network firewall rule", "A backup schedule"], correctIndex: 1, explanation: "Virtualization creates virtual (software-based) versions of physical resources like servers or storage." },
      { order: 2, question: "What is the role of a hypervisor?", options: ["To provide internet connectivity", "To create and manage virtual machines, allocating hardware resources to each", "To encrypt data at rest", "To monitor network traffic for threats"], correctIndex: 1, explanation: "A hypervisor manages virtual machines and their allocation of underlying physical resources." },
      { order: 3, question: "What is the key difference between a Type 1 and Type 2 hypervisor?", options: ["They are functionally identical", "Type 1 runs directly on hardware; Type 2 runs on top of an existing OS", "Type 2 is always faster than Type 1", "Only Type 1 supports virtual machines"], correctIndex: 1, explanation: "Type 1 (bare metal) runs directly on hardware; Type 2 runs on top of a host operating system." },
      { order: 4, question: "What does a virtual machine include that a container does not?", options: ["Application code", "Its own full guest operating system", "Network connectivity", "Storage"], correctIndex: 1, explanation: "A VM runs a complete separate OS; a container shares the host OS kernel instead." },
      { order: 5, question: "What is a key benefit of virtualization?", options: ["It guarantees zero cost", "Improved hardware utilisation by running multiple workloads on shared resources", "It eliminates the need for any networking", "It removes the need for backups"], correctIndex: 1, explanation: "Virtualization lets shared physical hardware run multiple isolated workloads efficiently." },
      { order: 6, question: "Why do containers typically start much faster than VMs?", options: ["Containers use more powerful hardware", "Containers share the host OS kernel instead of booting a separate full OS", "Containers don't actually run any code", "VMs are always run on slower hardware"], correctIndex: 1, explanation: "Skipping a full OS boot, since the kernel is shared with the host, makes containers start far faster than VMs." },
      { order: 7, question: "Why are containers generally more resource-efficient than VMs?", options: ["They require more memory per instance", "They avoid running a full separate OS per instance, using far less memory and disk", "They cannot run more than one at a time", "They always require dedicated physical hardware"], correctIndex: 1, explanation: "Without a full guest OS per instance, containers use significantly fewer resources than VMs." },
      { order: 8, question: "What does a VM snapshot capture?", options: ["Only the VM's network configuration", "The exact state of a VM's disk, memory, and configuration at a point in time", "Only the VM's name", "The physical host's hardware specifications"], correctIndex: 1, explanation: "A snapshot preserves a VM's full state, allowing restoration to that exact point later." },
      { order: 9, question: "What is VM migration used for?", options: ["Permanently deleting a virtual machine", "Moving a VM between physical hosts, often without downtime", "Encrypting a VM's storage", "Assigning a static IP address"], correctIndex: 1, explanation: "Migration relocates a VM to a different host, useful for maintenance or load balancing, often live without interrupting the workload." },
      { order: 10, question: "What risk does resource overcommitment carry?", options: ["It guarantees better performance always", "Performance problems if multiple VMs demand their full allocation simultaneously", "It prevents any VM from ever starting", "It has no real risk"], correctIndex: 1, explanation: "Overcommitment bets on not all VMs needing full resources at once — a risk if that assumption fails." },
      { order: 11, question: "What is a virtual network?", options: ["A physical cable connecting two servers", "A software-defined network replicating switching and routing functions in software", "A backup of network configuration files", "A firewall rule set"], correctIndex: 1, explanation: "Virtual networks replicate networking functionality in software, connecting virtual machines or containers." },
      { order: 12, question: "Why is virtualization foundational to cloud computing?", options: ["It has no real connection to cloud computing", "It enables safe, efficient multi-tenant infrastructure sharing across customers", "It only matters for on-premises data centres", "It replaces the need for any physical hardware at all"], correctIndex: 1, explanation: "Virtualization underlies cloud providers' ability to run many isolated customer workloads efficiently on shared physical hardware." },
    ]
  );

  // ── MODULE 5 — Cloud Storage ───────────────────────────────────────────────
  await createModule("module-5", "Cloud Storage", 5, "locked",
    [
      { order: 1, question: "What is object storage?", answer: "Object storage stores data as discrete objects, each with data, metadata, and a unique identifier, typically accessed over the internet via an API rather than a traditional file system — well suited to storing large amounts of unstructured data like images, videos, or backups.", example: "Storing millions of user-uploaded photos, each retrievable by a unique key rather than a file path, is a typical object storage use case." },
      { order: 2, question: "What is block storage?", answer: "Block storage divides data into fixed-size blocks, each with its own address, giving an operating system low-level, high-performance access similar to a traditional hard drive — commonly attached to virtual machines needing fast, flexible storage.", example: "The virtual \"hard drive\" attached to a cloud virtual machine, where the OS is installed, is typically block storage." },
      { order: 3, question: "What is file storage?", answer: "File storage organises data in a familiar hierarchical folder structure, accessed using standard file-sharing protocols, allowing multiple systems to read and write shared files simultaneously — similar to a traditional network file share.", example: "A shared drive that multiple virtual machines can mount and access simultaneously, using familiar file and folder paths, is file storage." },
      { order: 4, question: "When would you choose object storage over block storage?", answer: "Object storage suits large volumes of unstructured data accessed via API, especially when data doesn't change often and needs to scale to huge volumes — block storage suits workloads needing fast, low-level, frequently-changing access, like a database or OS disk.", example: "Storing years of archived log files is a good fit for object storage; the actively-used database disk on a running VM needs block storage instead." },
      { order: 5, question: "What are storage tiers, and why do cloud providers offer them?", answer: "Storage tiers offer different price/performance trade-offs for data based on how frequently it's accessed — frequently accessed (\"hot\") data costs more per GB but retrieves instantly, while rarely accessed (\"cold\" or archive) data costs far less but may take longer to retrieve.", example: "Recent customer data might sit in a hot tier for instant access, while data older than a year moves to a cheaper archive tier accessed only occasionally." },
      { order: 6, question: "What is data replication in cloud storage?", answer: "Replication automatically stores multiple copies of data, often across different physical locations, protecting against data loss from hardware failure and improving availability and durability.", example: "A cloud storage service automatically keeping three copies of every file across different physical drives protects against a single drive failure causing data loss." },
      { order: 7, question: "What is the difference between durability and availability in cloud storage?", answer: "Durability is the likelihood data won't be lost or corrupted over time. Availability is whether the data can actually be accessed when requested. A storage system can theoretically be extremely durable (data never lost) while briefly unavailable (temporarily inaccessible) during an outage.", example: "A service advertising \"eleven nines\" of durability is promising data essentially won't be lost, which is a separate guarantee from its uptime/availability percentage." },
      { order: 8, question: "What is a CDN (Content Delivery Network), and how does it relate to cloud storage?", answer: "A CDN caches and serves content from servers geographically closer to end users, reducing latency for frequently accessed content like images, videos, or web assets, often used together with cloud storage to distribute that stored content efficiently worldwide.", example: "A video streaming service storing its videos in cloud storage but delivering them to viewers via a CDN's nearby edge servers reduces buffering for users far from the original storage location." },
      { order: 9, question: "What is versioning in cloud storage?", answer: "Versioning keeps multiple historical versions of an object as it changes over time, allowing recovery of a previous version if a file is accidentally overwritten, corrupted, or deleted.", example: "Accidentally overwriting an important document can be undone by restoring an earlier version, if versioning was enabled on that storage." },
      { order: 10, question: "What is data lifecycle management in cloud storage?", answer: "Lifecycle management automatically transitions data between storage tiers, or deletes it entirely, based on defined rules and age — reducing cost by moving data to cheaper tiers (or removing it) once it's no longer frequently needed, without manual intervention.", example: "A rule automatically moving files older than 90 days to a cheaper archive tier, then deleting them entirely after 7 years, is data lifecycle management." },
      { order: 11, question: "What is the difference between backup and archive storage?", answer: "Backup storage keeps recent, recoverable copies of active data specifically for restoring after loss or corruption, typically retained for a shorter period. Archive storage retains data long-term, often for compliance or historical reasons, and is optimised for infrequent access at the lowest cost.", example: "A nightly backup of a database kept for 30 days serves a different purpose than a 7-year archive of financial records kept for regulatory compliance." },
      { order: 12, question: "Why does storage class choice matter for cost management in the cloud?", answer: "Storing all data in the most expensive, fastest-access tier regardless of actual access patterns wastes money — matching data to the appropriate tier based on how often it's really accessed is one of the most direct ways to control cloud storage costs.", example: "Leaving years of rarely-accessed log files in an expensive hot storage tier, instead of moving them to a cheaper archive tier, needlessly inflates a cloud bill." },
    ],
    [
      { order: 1, question: "What is object storage well suited for?", options: ["Low-level block access for an operating system disk", "Large amounts of unstructured data accessed via API", "Only structured relational database tables", "Real-time video encoding"], correctIndex: 1, explanation: "Object storage is designed for large-scale unstructured data, accessed through an API rather than a file system." },
      { order: 2, question: "What is block storage commonly used for?", options: ["Archiving decades-old records", "The attached disk of a virtual machine needing fast, low-level access", "Serving static website content globally", "Email storage only"], correctIndex: 1, explanation: "Block storage is typically used as the fast, low-level storage attached to a running VM." },
      { order: 3, question: "What characterises file storage?", options: ["Data addressed only by a unique object key", "A hierarchical folder structure accessible by multiple systems simultaneously", "Fixed-size blocks with no file structure", "Data that cannot be shared between systems"], correctIndex: 1, explanation: "File storage uses a familiar folder hierarchy, shareable across multiple systems at once." },
      { order: 4, question: "Which storage type would best suit millions of archived log files accessed occasionally?", options: ["Block storage", "Object storage", "In-memory cache only", "None of these are appropriate"], correctIndex: 1, explanation: "Object storage suits large volumes of infrequently accessed, unstructured data well." },
      { order: 5, question: "What do storage tiers primarily trade off?", options: ["Security versus convenience", "Cost per GB versus access speed/frequency", "Only geographic location", "Encryption strength versus performance"], correctIndex: 1, explanation: "Storage tiers balance cost against how quickly and frequently data needs to be accessed." },
      { order: 6, question: "What does data replication protect against?", options: ["Slow internet connections", "Data loss from hardware failure, by keeping multiple copies", "Unauthorised access", "High storage costs"], correctIndex: 1, explanation: "Replication maintains multiple copies of data, protecting against loss from a single point of failure." },
      { order: 7, question: "What is the difference between durability and availability?", options: ["They are the same measurement", "Durability is about data not being lost; availability is about data being accessible when needed", "Availability only applies to backups", "Durability only applies to block storage"], correctIndex: 1, explanation: "Durability concerns data loss over time; availability concerns whether data can be accessed right now." },
      { order: 8, question: "What does a CDN do?", options: ["Encrypts data at rest", "Caches and serves content from locations closer to end users to reduce latency", "Replaces the need for any storage", "Manages virtual machine scaling"], correctIndex: 1, explanation: "A CDN distributes cached content geographically to reduce latency for end users." },
      { order: 9, question: "What does versioning in cloud storage allow?", options: ["Faster upload speeds", "Recovery of a previous version of an object after an accidental change or deletion", "Automatic encryption of new files", "Unlimited free storage"], correctIndex: 1, explanation: "Versioning preserves historical copies of an object, allowing recovery from accidental overwrites or deletion." },
      { order: 10, question: "What does data lifecycle management automate?", options: ["User authentication", "Moving or deleting data between storage tiers based on age or rules", "Network routing", "Virtual machine scaling"], correctIndex: 1, explanation: "Lifecycle management automatically transitions or removes data according to defined age-based rules." },
      { order: 11, question: "What best distinguishes backup storage from archive storage?", options: ["They are identical in purpose", "Backup supports recovery of recent active data; archive retains data long-term for compliance/history", "Archive storage is always more expensive than backup", "Backups are never deleted"], correctIndex: 1, explanation: "Backups focus on recent recoverability; archives focus on long-term, infrequently accessed retention." },
      { order: 12, question: "Why does matching data to the correct storage tier matter for cost?", options: ["It has no effect on cost", "Storing rarely-accessed data in an expensive hot tier wastes money", "All storage tiers cost the same regardless of access pattern", "Only object storage has tiered pricing"], correctIndex: 1, explanation: "Matching access patterns to appropriately priced tiers is a direct, practical way to control cloud storage costs." },
    ]
  );

  // ── MODULE 6 — Cloud Networking and Cost ──────────────────────────────────
  await createModule("module-6", "Cloud Networking and Cost", 6, "locked",
    [
      { order: 1, question: "What is a virtual private cloud (VPC)?", answer: "A VPC is a logically isolated section of a cloud provider's network, dedicated to a single customer, where they can define their own IP address ranges, subnets, and network rules — similar in concept to a private, self-defined network within the shared cloud infrastructure.", example: "An organisation defines its own VPC with specific subnets for its web servers, application servers, and databases, isolated from other customers' resources." },
      { order: 2, question: "What is the difference between a public and private subnet in cloud networking?", answer: "A public subnet has a route to the internet, allowing resources within it to be reached from (or reach out to) the public internet directly. A private subnet has no direct internet route, keeping resources within it isolated from direct external access.", example: "A public-facing web server sits in a public subnet, while the database it talks to sits in a private subnet with no direct internet exposure." },
      { order: 3, question: "What is a load balancer, and why is it used?", answer: "A load balancer distributes incoming traffic across multiple backend servers or resources, improving reliability (if one server fails, traffic goes to the others) and allowing capacity to scale by adding more backend resources behind it.", example: "A load balancer spreading website traffic evenly across ten identical web servers means no single server gets overwhelmed, and traffic keeps flowing even if one server goes down." },
      { order: 4, question: "What is the pay-as-you-go pricing model?", answer: "Pay-as-you-go bills customers based on actual resource consumption — compute hours used, data stored, data transferred — with no long-term commitment required, offering flexibility but potentially higher per-unit cost than committed pricing options.", example: "Being billed only for the exact hours a virtual machine actually ran, rather than a fixed monthly fee regardless of usage, is pay-as-you-go pricing." },
      { order: 5, question: "What is the difference between on-demand and reserved/committed pricing?", answer: "On-demand pricing charges the standard rate with no commitment, offering maximum flexibility. Reserved or committed pricing offers a significant discount in exchange for committing to use (and pay for) a resource for a set period, like one or three years.", example: "A company running a server continuously for years might save significantly by committing to a one-year reserved rate instead of paying full on-demand price the whole time." },
      { order: 6, question: "What is a spot or preemptible instance?", answer: "Spot (or preemptible) instances offer spare cloud capacity at a steep discount, but the provider can reclaim that capacity with little notice if it's needed elsewhere — well suited to flexible, interruption-tolerant workloads rather than critical, always-on systems.", example: "A batch data-processing job that can pause and resume later is a good candidate for cheap spot instances; a customer-facing production database is not." },
      { order: 7, question: "What is a budget alert in cloud cost management?", answer: "A budget alert automatically notifies relevant people when spending approaches or exceeds a defined threshold, helping catch unexpected cost spikes — like a misconfigured resource left running — before they become a large, surprise bill.", example: "An alert firing when monthly cloud spend crosses 80% of the budgeted amount gives the team time to investigate before the month ends." },
      { order: 8, question: "What is resource tagging, and how does it help with cost management?", answer: "Tagging attaches metadata labels — like project name, department, or environment — to cloud resources, making it possible to break down costs by tag and see exactly which team, project, or environment is driving spend.", example: "Tagging every resource with a project name lets finance see exactly how much each individual project costs each month, rather than one undifferentiated total bill." },
      { order: 9, question: "What is idle resource waste, and how does it commonly happen?", answer: "Idle resource waste is money spent on cloud resources that are provisioned but not actually being used productively — often from forgetting to shut down test environments, oversized resources for the actual workload, or unused storage never cleaned up.", example: "A development team spinning up test servers for a demo, then forgetting to shut them down afterward, quietly accumulates unnecessary cost for weeks." },
      { order: 10, question: "What is the general trade-off between cost and performance in cloud architecture?", answer: "Higher performance — faster compute, premium storage tiers, more redundancy — generally costs more, and cost optimisation often means deliberately choosing \"good enough\" performance for a given workload rather than always defaulting to the most powerful (and expensive) option available.", example: "Using a smaller, cheaper virtual machine size that still comfortably meets an application's actual performance needs, instead of an oversized instance never fully utilised, controls cost without harming the user experience." },
      { order: 11, question: "What is a DNS-based routing service used for in cloud networking?", answer: "DNS-based routing services translate domain names to the appropriate cloud resources and can add intelligent routing logic — like directing users to the geographically nearest region, or automatically routing away from an unhealthy resource.", example: "A global application using DNS-based routing sends European users to a European region and US users to a US region automatically, based on their location." },
      { order: 12, question: "Why is understanding data transfer costs important in cloud architecture?", answer: "Many cloud providers charge for data transferred out of their network (and sometimes between regions or availability zones), which can become a significant, easily overlooked cost if architecture isn't designed with data flow and transfer patterns in mind.", example: "An architecture that repeatedly transfers large amounts of data between two different regions unnecessarily can rack up meaningful data transfer charges that a better-designed layout would have avoided." },
    ],
    [
      { order: 1, question: "What is a VPC?", options: ["A physical data centre", "A logically isolated, customer-defined section of a cloud provider's network", "A type of storage tier", "A billing report"], correctIndex: 1, explanation: "A VPC is an isolated, customer-controlled virtual network within the cloud provider's infrastructure." },
      { order: 2, question: "What distinguishes a public subnet from a private subnet?", options: ["A public subnet has a route to the internet; a private subnet does not", "They are functionally identical", "Only private subnets can host virtual machines", "Public subnets cannot contain any resources"], correctIndex: 0, explanation: "A public subnet allows direct internet routing; a private subnet is isolated from direct external access." },
      { order: 3, question: "What does a load balancer do?", options: ["Encrypts traffic between servers", "Distributes incoming traffic across multiple backend resources", "Stores backup copies of data", "Assigns static IP addresses"], correctIndex: 1, explanation: "Load balancers spread traffic across backend resources for reliability and scalability." },
      { order: 4, question: "What does pay-as-you-go pricing charge based on?", options: ["A fixed annual fee regardless of usage", "Actual resource consumption, with no long-term commitment", "The number of employees at a company", "A one-time upfront payment only"], correctIndex: 1, explanation: "Pay-as-you-go bills for actual usage without requiring a commitment." },
      { order: 5, question: "What do reserved/committed pricing plans offer in exchange for a commitment?", options: ["No discount at all", "A significant discount compared to on-demand pricing", "Unlimited free usage", "Guaranteed zero downtime"], correctIndex: 1, explanation: "Committing to usage over a period, like one or three years, typically earns a substantial price discount." },
      { order: 6, question: "What is a key risk of using spot/preemptible instances?", options: ["They are always more expensive than on-demand", "The provider can reclaim the capacity with little notice", "They cannot run any workload at all", "They require a long-term contract"], correctIndex: 1, explanation: "Spot instances are cheap but can be reclaimed by the provider with minimal warning, unsuitable for critical uninterruptible workloads." },
      { order: 7, question: "What is the purpose of a budget alert?", options: ["To automatically shut down all resources", "To notify relevant people when spending nears or exceeds a defined threshold", "To increase cloud spending automatically", "To generate marketing reports"], correctIndex: 1, explanation: "Budget alerts flag rising costs early, before they become a large surprise bill." },
      { order: 8, question: "What does resource tagging enable?", options: ["Faster network speeds", "Breaking down costs by project, department, or environment", "Automatic data encryption", "Reduced storage costs automatically"], correctIndex: 1, explanation: "Tags let organisations attribute cloud spend to specific projects, teams, or environments." },
      { order: 9, question: "What commonly causes idle resource waste?", options: ["Efficient resource tagging", "Forgetting to shut down unused test environments or oversized resources", "Using reserved pricing", "Enabling budget alerts"], correctIndex: 1, explanation: "Leftover, unused, or oversized resources are a common and often overlooked source of unnecessary cloud cost." },
      { order: 10, question: "What does cost optimisation often involve regarding performance?", options: ["Always choosing the most powerful option available", "Choosing \"good enough\" performance that matches actual workload needs", "Ignoring performance entirely", "Only optimising cost for storage, never compute"], correctIndex: 1, explanation: "Cost optimisation often means right-sizing resources to actual needs rather than defaulting to maximum performance." },
      { order: 11, question: "What can DNS-based routing services help achieve?", options: ["Only static IP assignment", "Routing users to the nearest healthy region or resource automatically", "Data encryption at rest", "Manual failover with no automation"], correctIndex: 1, explanation: "DNS-based routing can intelligently direct traffic based on geography or resource health." },
      { order: 12, question: "Why should architects be mindful of data transfer costs?", options: ["Data transfer is always free in the cloud", "Many providers charge for data leaving their network or moving between regions, which can add up unexpectedly", "Data transfer costs only apply to storage, never compute", "It only matters for on-premises infrastructure"], correctIndex: 1, explanation: "Overlooked data transfer charges, especially cross-region, can become a significant and avoidable cost if not designed around." },
    ]
  );

  // ── MODULE 7 — Cloud Fundamentals Review ──────────────────────────────────
  await createModule("module-7", "Cloud Fundamentals Review", 7, "locked",
    [
      { order: 1, question: "What are the five essential characteristics of cloud computing, recapped together?", answer: "On-demand self-service, broad network access, resource pooling, rapid elasticity, and measured service. All five together are commonly used to distinguish genuine cloud computing from simply hosting something on someone else's server.", example: "A hosted server that requires a phone call and manual setup for every change lacks on-demand self-service and rapid elasticity — arguably not fully \"cloud\" by this definition, even if it's remotely hosted." },
      { order: 2, question: "What is \"broad network access\" as an essential cloud characteristic?", answer: "Broad network access means cloud services are available over the network and accessible through standard mechanisms from a wide range of client devices — laptops, phones, tablets — not tied to one specific type of device or location.", example: "Being able to manage your cloud resources equally well from a laptop browser or a mobile app demonstrates broad network access." },
      { order: 3, question: "Recap: what's the core difference between IaaS, PaaS, and SaaS?", answer: "IaaS provides raw infrastructure with the customer managing everything above it. PaaS provides a managed platform for building and running applications. SaaS provides a complete, ready-to-use application. Responsibility shifts progressively toward the provider from IaaS to PaaS to SaaS.", example: "Renting a bare virtual server is IaaS; deploying code to a managed platform is PaaS; using a finished web application is SaaS." },
      { order: 4, question: "Recap: what's the core difference between public, private, and hybrid cloud?", answer: "Public cloud is shared, provider-owned infrastructure. Private cloud is dedicated to one organisation. Hybrid cloud combines both public and private/on-premises environments together.", example: "Choosing between these often comes down to balancing cost and convenience (public) against control and compliance needs (private), with hybrid offering a middle path." },
      { order: 5, question: "Recap: what's the core difference between a VM and a container?", answer: "A VM virtualizes an entire computer including a full guest OS, offering strong isolation at the cost of more overhead. A container shares the host OS kernel, offering much lighter weight and faster startup, with slightly less isolation than a full VM.", example: "Choosing VMs versus containers often comes down to whether you need the strongest possible isolation (VMs) or fast, efficient, high-density deployment (containers)." },
      { order: 6, question: "What is a common exam-style trap involving \"serverless\" terminology?", answer: "Assuming \"serverless\" literally means no servers are involved is a common misconception — servers are still very much involved, just entirely managed by the provider rather than the customer.", example: "A question asking \"where does serverless code actually execute\" is testing whether you understand it still runs on real, provider-managed servers." },
      { order: 7, question: "What is a common exam-style trap involving object versus block storage?", answer: "A scenario describing a database or OS disk needing fast, low-level, frequently-changing access is testing block storage, while a scenario describing massive, infrequently-changing unstructured data accessed via API is testing object storage — mixing these up is a very common error.", example: "A scenario describing \"storing millions of user photos accessed occasionally\" is testing object storage, not block storage, despite both being valid \"storage\" answers on a surface read." },
      { order: 8, question: "What is a common exam-style trap involving durability versus availability?", answer: "These two terms sound similar but measure different things — durability is about whether data is ever lost, while availability is about whether the system can be reached right now. A question about \"can I access my file at this moment\" is about availability, not durability.", example: "A brief planned maintenance outage affects availability, not durability — the data itself remains perfectly safe and unlost throughout." },
      { order: 9, question: "What is a common exam-style trap involving CapEx versus OpEx and cloud adoption?", answer: "Questions may describe a scenario emphasising \"avoiding large upfront investment\" or \"paying only for what you use\" — this language points to the CapEx-to-OpEx shift as a key cloud computing benefit, even if the term \"OpEx\" itself isn't used directly in the question.", example: "A scenario describing a startup avoiding a large upfront hardware purchase by using cloud services instead is testing understanding of the CapEx-to-OpEx shift." },
      { order: 10, question: "What is a good general strategy for scenario-based cloud fundamentals questions?", answer: "Identify exactly which core concept the scenario is describing (a specific service model, deployment model, storage type, or essential characteristic) before looking at the options, and be alert for options that sound plausible but actually describe a related but distinct concept.", example: "A question describing \"resources shared efficiently across many customers\" is testing resource pooling specifically, not a similar-sounding but distinct concept like elasticity." },
      { order: 11, question: "Why might a beginner confuse \"scalability\" with \"elasticity\"?", answer: "The terms are related but distinct: scalability is the general ability of a system to handle growth, whether done manually or automatically. Elasticity specifically refers to automatic, rapid scaling up and down to match real-time demand — elasticity is really a specific, more dynamic form of scalability.", example: "A system that can be scaled up by manually adding more servers over a few days is scalable but not particularly elastic; automatic real-time scaling is what makes a system elastic." },
      { order: 12, question: "What ties all the concepts in this course together as a foundation for further study?", answer: "Cloud computing's essential characteristics, service models, deployment models, virtualization, storage options, and networking/cost concepts together form the vocabulary and mental model needed to reason about more advanced cloud architecture decisions, like those covered in a dedicated cloud architecture course.", example: "Understanding the trade-off between control and management overhead across service models directly informs later architecture decisions about how to design a specific, real system." },
    ],
    [
      { order: 1, question: "Which of these is NOT one of the five essential characteristics of cloud computing?", options: ["On-demand self-service", "Resource pooling", "Guaranteed zero cost", "Measured service"], correctIndex: 2, explanation: "The five essential characteristics are on-demand self-service, broad network access, resource pooling, rapid elasticity, and measured service — \"guaranteed zero cost\" isn't one of them." },
      { order: 2, question: "What does \"broad network access\" mean as an essential cloud characteristic?", options: ["Only one type of device can access the service", "Services are accessible over the network from a wide range of standard client devices", "The service has no network connectivity", "Access is restricted to one geographic region"], correctIndex: 1, explanation: "Broad network access means availability across standard mechanisms and a wide range of devices, not device- or location-locked." },
      { order: 3, question: "Which service model gives the customer the least infrastructure management responsibility?", options: ["IaaS", "PaaS", "SaaS", "They are all identical"], correctIndex: 2, explanation: "SaaS shifts nearly all infrastructure management to the provider, leaving the customer with the least responsibility." },
      { order: 4, question: "Which deployment model combines public and private/on-premises infrastructure?", options: ["Public cloud", "Private cloud", "Hybrid cloud", "Community cloud"], correctIndex: 2, explanation: "Hybrid cloud specifically combines public cloud with private or on-premises infrastructure." },
      { order: 5, question: "What is the main trade-off between VMs and containers?", options: ["Containers offer stronger isolation but are heavier", "VMs offer stronger isolation with more overhead; containers are lighter but share the host kernel", "There is no meaningful trade-off between them", "Only VMs can run more than one instance"], correctIndex: 1, explanation: "VMs provide fuller isolation at higher overhead; containers are lighter and faster but share the host OS kernel." },
      { order: 6, question: "What is the common misconception about \"serverless\" computing?", options: ["That it is always more expensive", "That there are literally no servers involved", "That it cannot scale", "That it requires manual provisioning"], correctIndex: 1, explanation: "Serverless still runs on real, provider-managed servers — the customer just never manages them directly." },
      { order: 7, question: "A scenario describes storing millions of rarely-accessed photos via an API. Which storage type does this describe?", options: ["Block storage", "Object storage", "In-memory cache", "None of these"], correctIndex: 1, explanation: "Large-scale unstructured data accessed via API is a classic object storage use case." },
      { order: 8, question: "A brief planned maintenance outage primarily affects which property?", options: ["Durability", "Availability", "Elasticity", "Resource pooling"], correctIndex: 1, explanation: "A temporary inability to access data affects availability; the data itself remains durable (not lost)." },
      { order: 9, question: "A scenario describing \"avoiding a large upfront hardware purchase\" points to which cloud computing shift?", options: ["OpEx toward CapEx", "CapEx toward OpEx", "Public toward private cloud", "Block toward object storage"], correctIndex: 1, explanation: "Avoiding upfront capital investment in favour of ongoing usage-based spend is the CapEx-to-OpEx shift cloud computing enables." },
      { order: 10, question: "What is the best general strategy for scenario-based cloud fundamentals questions?", options: ["Always pick the first option listed", "Identify exactly which core concept the scenario describes before evaluating the options", "Ignore the scenario and focus only on keywords", "Assume every question is about cost"], correctIndex: 1, explanation: "Pinpointing the specific concept being tested makes distinguishing close, plausible-sounding wrong answers much easier." },
      { order: 11, question: "What is the relationship between scalability and elasticity?", options: ["They mean exactly the same thing in every context", "Elasticity is a specific, automatic, rapid form of the broader concept of scalability", "Scalability only applies to storage, elasticity only to compute", "Elasticity is unrelated to scalability"], correctIndex: 1, explanation: "Elasticity is a more dynamic, automatic subset of the broader idea of scalability." },
      { order: 12, question: "Why does this foundational course matter for further cloud study?", options: ["It has no connection to more advanced topics", "It builds the vocabulary and mental models needed to reason about cloud architecture decisions", "It replaces the need to ever learn about specific cloud providers", "It only matters for exam purposes, not real work"], correctIndex: 1, explanation: "These fundamentals directly underpin the reasoning needed for more advanced architecture and design decisions later." },
    ]
  );

  console.log("Done — binary-cloud created fresh with 7 modules, ~168 flashcard+quiz items.");
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
