/**
 * Content expansion: Agile & Scrum Foundations course (id: "csm").
 * Same pattern as expand-itil-v4.js — see that file's header for how to run
 * this. Adds 6 more flashcards + 6 more quiz questions to each of the 7
 * modules (cards/questions 7-12), roughly doubling the course.
 *
 * CHECK BEFORE RUNNING: a live check on 2026-08-29 found this course
 * actually has 8 modules, not 7 — same gap as expand-itil-v4.js. Confirm
 * the real module count/ids in Firestore before running.
 */

const admin = require("firebase-admin");
admin.initializeApp({ credential: admin.credential.applicationDefault() });

const db = admin.firestore();

async function addFlashcards(courseId, moduleId, cards, startIndex) {
  const col = db
    .collection("courses").doc(courseId)
    .collection("modules").doc(moduleId)
    .collection("flashcards");
  for (let i = 0; i < cards.length; i++) {
    await col.doc(`card-${startIndex + i}`).set(cards[i]);
  }
}

async function addQuiz(courseId, moduleId, questions, startIndex) {
  const col = db
    .collection("courses").doc(courseId)
    .collection("modules").doc(moduleId)
    .collection("quiz");
  for (let i = 0; i < questions.length; i++) {
    await col.doc(`q-${startIndex + i}`).set(questions[i]);
  }
}

async function setSubtitle(courseId, moduleId, flashcardCount, quizCount) {
  await db
    .collection("courses").doc(courseId)
    .collection("modules").doc(moduleId)
    .set({ subtitle: `${flashcardCount} flashcards · ${quizCount} questions` }, { merge: true });
}

async function expandModule(moduleId, flashcards, quiz) {
  await addFlashcards("csm", moduleId, flashcards, 7);
  await addQuiz("csm", moduleId, quiz, 7);
  await setSubtitle("csm", moduleId, 6 + flashcards.length, 6 + quiz.length);
  console.log(`csm/${moduleId}: +${flashcards.length} flashcards, +${quiz.length} quiz questions`);
}

async function main() {
  // ── MODULE 1 — Introduction to Agile and Scrum ───────────────────────────
  await expandModule("module-1",
    [
      { order: 7, question: "How does Agile differ from traditional Waterfall project management?", answer: "Waterfall plans an entire project upfront and moves through fixed sequential phases (requirements, design, build, test, release), with change discouraged once a phase is complete. Agile plans and delivers in short cycles, expecting and welcoming change throughout.", example: "A Waterfall team spends six months writing a full spec before coding starts; an Agile team starts coding in week two and adjusts the plan as they learn." },
      { order: 8, question: "What does \"iterative and incremental\" mean in Agile development?", answer: "Iterative means repeating cycles of work, refining the product each time. Incremental means each cycle adds a usable piece of functionality rather than delivering everything at once. Agile combines both — small, usable pieces, refined and built upon repeatedly.", example: "Each sprint adds a working feature (incremental) and later sprints improve on earlier ones based on feedback (iterative)." },
      { order: 9, question: "Where did the Agile Manifesto come from?", answer: "In 2001, seventeen software practitioners met in Snowbird, Utah, frustrated with heavyweight, documentation-heavy development processes. They wrote the Agile Manifesto to capture a shared set of values and principles for lighter, more adaptive ways of working.", example: "The meeting produced just four values and twelve principles — deliberately short and practical rather than a detailed methodology." },
      { order: 10, question: "How does \"inspect and adapt\" relate to empiricism?", answer: "Inspect and adapt is empiricism in action: regularly examining the current state of work (inspect) and adjusting the approach based on what is learned (adapt). Nearly every Scrum event exists to create a formal opportunity to inspect and adapt something.", example: "The Daily Scrum inspects progress toward the Sprint Goal; the team adapts the day's plan based on what they find." },
      { order: 11, question: "What other Agile frameworks exist besides Scrum?", answer: "Kanban focuses on visualising and limiting work in progress with continuous flow. Extreme Programming (XP) adds engineering practices like pair programming and test-driven development. Lean focuses on eliminating waste. Scrum is the most widely adopted, but teams sometimes blend elements of several.", example: "A team might run Scrum for planning and reviews but adopt XP practices like automated testing for how the code itself gets written." },
      { order: 12, question: "Is Scrum a methodology or a framework, and why does the distinction matter?", answer: "Scrum is deliberately a lightweight framework, not a full methodology — it defines roles, events, and artifacts, but intentionally leaves engineering practices, estimation techniques, and many implementation details up to the team to decide.", example: "Scrum says a Sprint must have a Sprint Review; it does not say whether the team should use story points or hours to estimate — that choice is left to the team." },
    ],
    [
      { order: 7, question: "What best describes the difference between Waterfall and Agile?", options: ["They are the same approach with different names", "Waterfall plans upfront in sequential phases; Agile delivers and adapts in short cycles", "Agile requires more documentation than Waterfall", "Waterfall is only used for software"], correctIndex: 1, explanation: "Waterfall is sequential and plan-driven; Agile is iterative, incremental, and adapts based on feedback." },
      { order: 8, question: "What does \"incremental\" mean in Agile development?", options: ["Repeating the same cycle without change", "Each cycle adds a usable piece of functionality", "Increasing the team size each sprint", "Raising the budget over time"], correctIndex: 1, explanation: "Incremental delivery means each cycle produces a usable addition to the product rather than delivering everything at the very end." },
      { order: 9, question: "Where and when was the Agile Manifesto written?", options: ["Silicon Valley, 1995", "Snowbird, Utah, 2001", "London, 2010", "Online, 2020"], correctIndex: 1, explanation: "Seventeen practitioners wrote the Agile Manifesto in Snowbird, Utah, in 2001." },
      { order: 10, question: "\"Inspect and adapt\" is best described as:", options: ["A one-time planning exercise", "Empiricism in practice — regularly examining work and adjusting the approach", "A Scrum Master's job title", "A synonym for the Sprint Backlog"], correctIndex: 1, explanation: "Inspect and adapt is how empiricism plays out in Scrum — most events exist to create a chance to do both." },
      { order: 11, question: "Which of these is another Agile framework besides Scrum?", options: ["ITIL", "Kanban", "COBIT", "PRINCE2"], correctIndex: 1, explanation: "Kanban is an Agile method focused on visualising and limiting work in progress; ITIL, COBIT, and PRINCE2 are not Agile frameworks." },
      { order: 12, question: "Why is Scrum described as a framework rather than a full methodology?", options: ["Because it has no rules at all", "Because it defines roles, events, and artifacts but leaves many implementation details to the team", "Because it only applies to software", "Because it replaced all other frameworks"], correctIndex: 1, explanation: "Scrum is deliberately minimal — it provides structure while leaving many specifics, like estimation technique, up to the team." },
    ]
  );

  // ── MODULE 2 — The Scrum Framework ───────────────────────────────────────
  await expandModule("module-2",
    [
      { order: 7, question: "What is a \"timebox\" in Scrum?", answer: "A timebox is a fixed maximum duration for an event or activity. Every Scrum event is timeboxed — it may end early once its purpose is achieved, but it must never run longer than its maximum duration.", example: "A Daily Scrum is timeboxed to 15 minutes — the team can finish sooner if done, but it should never run to 25 minutes." },
      { order: 8, question: "What happens to Sprint Backlog items not finished by the end of the Sprint?", answer: "Unfinished items return to the Product Backlog to be re-estimated and re-prioritised — they are not automatically carried over to the next Sprint. The Product Owner decides whether and when to reschedule them.", example: "A story that's 80% done at Sprint end goes back to the backlog; the team might re-estimate the remaining work as a smaller story for a future sprint." },
      { order: 9, question: "When is the Increment formally inspected?", answer: "While work may be completed throughout the Sprint, the Increment as a whole is formally inspected at the Sprint Review, where the Scrum Team and stakeholders examine what was built and decide what to do next.", example: "A feature finished on day 3 of a two-week sprint is still formally reviewed and demoed at the Sprint Review on day 14, alongside everything else completed." },
      { order: 10, question: "What is the Product Goal?", answer: "The Product Goal is the long-term objective for the product, describing a future state the Scrum Team works toward across multiple Sprints. Each Sprint Goal is a step toward achieving the Product Goal.", example: "A Product Goal might be \"become the leading budgeting app for freelancers\" — individual Sprint Goals chip away at that over many sprints." },
      { order: 11, question: "What is the difference between estimating in story points versus hours?", answer: "Story points measure relative effort, complexity, and uncertainty rather than exact time, making estimates less sensitive to interruptions and individual speed. Hours estimate a specific time duration, which can vary wildly between team members and is harder to keep consistent.", example: "A story might be estimated as \"5 story points\" regardless of who does it, while an hour-based estimate might differ depending on who is assigned." },
      { order: 12, question: "What is a team's \"capacity\" in Sprint Planning?", answer: "Capacity is the amount of time a team actually has available to work during a Sprint, accounting for holidays, meetings, planned leave, and other commitments — it is usually lower than the theoretical maximum working hours.", example: "A team with two developers on planned leave during the sprint has reduced capacity and should commit to less work than usual." },
    ],
    [
      { order: 7, question: "What does it mean for a Scrum event to be \"timeboxed\"?", options: ["It must always use the full duration", "It has a fixed maximum duration but can end early", "It has no time limit", "It can be skipped if the team is busy"], correctIndex: 1, explanation: "A timebox sets a maximum duration; the event can end sooner but must never exceed the limit." },
      { order: 8, question: "What happens to Sprint Backlog items not completed by Sprint end?", options: ["They are discarded permanently", "They automatically roll into the next sprint unchanged", "They return to the Product Backlog to be re-estimated and re-prioritised", "The team must work overtime to finish them"], correctIndex: 2, explanation: "Unfinished work goes back to the Product Backlog — the Product Owner decides if and when to reschedule it." },
      { order: 9, question: "When is the Increment formally inspected by the whole Scrum Team and stakeholders?", options: ["Daily, in the Daily Scrum", "At the Sprint Review", "Only when the Product Owner requests it", "Never — it is inspected informally only"], correctIndex: 1, explanation: "The Sprint Review is the formal event where the Increment is inspected together with stakeholders." },
      { order: 10, question: "What is the Product Goal?", options: ["The task list for today", "The long-term objective the Scrum Team works toward across multiple Sprints", "A synonym for the Sprint Goal", "A KPI set by senior management"], correctIndex: 1, explanation: "The Product Goal is the long-term target; each Sprint Goal is a step toward it." },
      { order: 11, question: "What do story points primarily measure?", options: ["Exact hours of work", "Relative effort, complexity, and uncertainty", "Team headcount", "Lines of code"], correctIndex: 1, explanation: "Story points estimate relative size rather than precise time, making estimates more consistent across a team." },
      { order: 12, question: "What is \"capacity\" in Sprint Planning?", options: ["The maximum size of the Product Backlog", "The amount of time a team actually has available to work in the Sprint", "The number of Scrum events per sprint", "The velocity from the previous sprint"], correctIndex: 1, explanation: "Capacity accounts for leave, meetings, and other commitments to estimate realistic available working time." },
    ]
  );

  // ── MODULE 3 — Scrum Roles ────────────────────────────────────────────────
  await expandModule("module-3",
    [
      { order: 7, question: "What is \"servant leadership\" as it applies to the Scrum Master?", answer: "Servant leadership means the Scrum Master's role is to serve the team, the Product Owner, and the organisation — removing obstacles and enabling others to do their best work — rather than directing or commanding people the way a traditional manager might.", example: "Instead of telling developers how to solve a technical problem, a servant-leader Scrum Master asks questions that help the team find their own solution." },
      { order: 8, question: "Who are \"stakeholders\" in a Scrum context?", answer: "Stakeholders are people outside the Scrum Team who have an interest in the product — customers, users, sponsors, or other departments. They are invited to the Sprint Review to give feedback but are not part of the Scrum Team itself.", example: "A marketing director attending the Sprint Review to see new features and share launch feedback is acting as a stakeholder, not a team member." },
      { order: 9, question: "Is there a hierarchy within the Developers on a Scrum Team?", answer: "No — Developers are not organised into sub-teams or given hierarchical titles within Scrum. They are accountable together as a group for creating the Increment each Sprint, regardless of individual specialisms like design, testing, or coding.", example: "A senior engineer has no formal authority over a junior engineer within the Scrum Team structure — decisions about the work are made collectively." },
      { order: 10, question: "Why must the Product Owner be one person, not a committee?", answer: "A single Product Owner ensures clear, fast, and consistent decision-making about priorities. A committee can still advise the Product Owner, but only one person is accountable for the Product Backlog to avoid conflicting or delayed decisions.", example: "If three stakeholders disagreed on priority and all had equal authority, the team could receive contradictory instructions — a single Product Owner prevents that." },
      { order: 11, question: "Who does the Scrum Master serve besides the Development Team and Product Owner?", answer: "The Scrum Master also serves the wider organisation, helping it understand Scrum, planning Scrum adoption, and working with other Scrum Masters to increase the effectiveness of Scrum's application more broadly.", example: "A Scrum Master coaching other departments on how to write better user stories for their own backlogs is serving the organisation, not just their own team." },
      { order: 12, question: "What are \"T-shaped\" skills and why do they matter for cross-functional teams?", answer: "T-shaped skills describe someone with deep expertise in one area (the vertical stroke of the T) but working knowledge across several others (the horizontal stroke). Teams with T-shaped members are more flexible, since people can help outside their primary specialism when needed.", example: "A backend developer who can also write basic frontend code or perform manual testing reduces bottlenecks when frontend work piles up." },
    ],
    [
      { order: 7, question: "What best describes \"servant leadership\" for a Scrum Master?", options: ["Directing the team's technical decisions", "Serving the team by removing obstacles and enabling their best work", "Managing performance reviews", "Assigning daily tasks to developers"], correctIndex: 1, explanation: "Servant leadership means enabling others rather than commanding them — a key distinction from a traditional manager." },
      { order: 8, question: "Who are stakeholders in Scrum?", options: ["Members of the Development Team", "People outside the Scrum Team with an interest in the product", "Only the Product Owner", "Only senior executives"], correctIndex: 1, explanation: "Stakeholders are external to the Scrum Team — customers, sponsors, other departments — and give feedback, typically at the Sprint Review." },
      { order: 9, question: "Is there a formal hierarchy among Developers on a Scrum Team?", options: ["Yes, seniority determines authority", "No, Developers are accountable together without sub-teams or titles", "Only if the team has more than 10 people", "Yes, but only for technical decisions"], correctIndex: 1, explanation: "Scrum does not define sub-teams or hierarchical titles among Developers — they are collectively accountable." },
      { order: 10, question: "Why is the Product Owner a single person rather than a committee?", options: ["Because committees are against company policy", "To ensure clear, fast, and consistent prioritisation decisions", "Because only one person is allowed to talk to stakeholders", "Because Scrum limits team size to one decision-maker"], correctIndex: 1, explanation: "A single accountable Product Owner avoids the conflicting instructions a committee could produce." },
      { order: 11, question: "Besides the team and Product Owner, who else does the Scrum Master serve?", options: ["No one else", "The wider organisation, helping it understand and adopt Scrum", "Only external stakeholders", "Only the Development Team's direct manager"], correctIndex: 1, explanation: "The Scrum Master also works to increase Scrum's effectiveness across the organisation, not just within one team." },
      { order: 12, question: "What does a \"T-shaped\" skill set describe?", options: ["A person who only knows one skill deeply", "Deep expertise in one area plus working knowledge across several others", "A team structure with a single leader", "A type of user story"], correctIndex: 1, explanation: "T-shaped people have one area of deep expertise and broader, working-level skills elsewhere — useful for flexible, cross-functional teams." },
    ]
  );

  // ── MODULE 4 — Scrum Events ────────────────────────────────────────────────
  await expandModule("module-4",
    [
      { order: 7, question: "What is the maximum timebox for the Sprint Review?", answer: "The Sprint Review is timeboxed to a maximum of four hours for a one-month Sprint, proportionally shorter for shorter Sprints — typically around two hours for a two-week sprint.", example: "A team on two-week sprints keeps their Sprint Review to about two hours, covering the demo and stakeholder discussion." },
      { order: 8, question: "What is the maximum timebox for the Sprint Retrospective?", answer: "The Sprint Retrospective is timeboxed to a maximum of three hours for a one-month Sprint, proportionally shorter for shorter Sprints — typically around ninety minutes for a two-week sprint. It concludes the Sprint.", example: "After a two-week sprint, the team spends about an hour on their retrospective before starting the next Sprint Planning." },
      { order: 9, question: "Can the Daily Scrum be skipped if there's nothing new to report?", answer: "No — the Daily Scrum is a required event and should happen every working day of the Sprint. Its format can vary, but skipping it removes the team's regular opportunity to inspect progress and adapt the plan.", example: "Even during a quiet week, the team still holds a brief Daily Scrum rather than assuming there's nothing worth discussing." },
      { order: 10, question: "Who is required to attend the Daily Scrum?", answer: "The Developers are required to attend, since it is their event for planning the next 24 hours of work. The Product Owner and Scrum Master attend if they are actively doing Sprint Backlog work themselves; otherwise their attendance is optional.", example: "A Product Owner who spends the day on customer research rather than development work isn't required at the Daily Scrum, though they may still choose to join." },
      { order: 11, question: "What should happen if a team finishes all planned work before the Sprint ends?", answer: "The team can pull in additional Product Backlog items in consultation with the Product Owner, as long as it doesn't compromise quality or the Sprint Goal — Scrum does not expect teams to simply stop working once the plan is complete.", example: "With two days left and the Sprint Goal met, the team picks up the next-highest priority backlog item rather than sitting idle." },
      { order: 12, question: "How does a Sprint Review differ from a plain \"demo\"?", answer: "A Sprint Review is collaborative — the Scrum Team and stakeholders discuss what was built, why, what's next, and adapt the Product Backlog together. A plain demo is one-directional: showing off finished work with little discussion or influence on future priorities.", example: "A Sprint Review where stakeholders ask questions and reprioritise the backlog based on what they saw is doing far more than a scripted feature walkthrough." },
    ],
    [
      { order: 7, question: "What is the maximum timebox for a Sprint Review on a one-month Sprint?", options: ["One hour", "Two hours", "Four hours", "Eight hours"], correctIndex: 2, explanation: "The Sprint Review is timeboxed to a maximum of four hours for a one-month Sprint, proportionally shorter for shorter sprints." },
      { order: 8, question: "What is the maximum timebox for a Sprint Retrospective on a one-month Sprint?", options: ["One hour", "Three hours", "Four hours", "Eight hours"], correctIndex: 1, explanation: "The Sprint Retrospective is timeboxed to a maximum of three hours for a one-month Sprint." },
      { order: 9, question: "Can the Daily Scrum be skipped if the team feels there's nothing to discuss?", options: ["Yes, whenever the team agrees", "No, it is a required event that should happen every working day", "Only the Scrum Master can decide to skip it", "Only during the last week of a Sprint"], correctIndex: 1, explanation: "The Daily Scrum is a required Scrum event and should not be skipped, even if its content varies day to day." },
      { order: 10, question: "Who is required to attend the Daily Scrum?", options: ["Only the Scrum Master", "Only the Product Owner", "The Developers doing the Sprint Backlog work", "All company stakeholders"], correctIndex: 2, explanation: "The Daily Scrum is for the Developers to plan their next 24 hours; others attend only if they are doing that work themselves." },
      { order: 11, question: "What should a team do if it finishes all planned Sprint work early?", options: ["Stop working until the Sprint ends", "Pull in more backlog items in consultation with the Product Owner", "Extend the Sprint length", "Start the next Sprint Planning immediately"], correctIndex: 1, explanation: "Teams can take on more work if capacity allows, in consultation with the Product Owner, without compromising quality or the Sprint Goal." },
      { order: 12, question: "What makes a Sprint Review different from a plain demo?", options: ["A Sprint Review is longer", "A Sprint Review is collaborative and can reshape the Product Backlog; a demo is one-directional", "There is no real difference", "A demo requires more preparation"], correctIndex: 1, explanation: "The Sprint Review involves discussion and collaboration on what comes next, not just a one-way showcase of finished work." },
    ]
  );

  // ── MODULE 5 — Scrum Artifacts ────────────────────────────────────────────
  await expandModule("module-5",
    [
      { order: 7, question: "What is the Fibonacci-like sequence often used for story points?", answer: "Many teams estimate story points using a modified Fibonacci sequence (1, 2, 3, 5, 8, 13, 21...) because the growing gaps between numbers reflect how estimation uncertainty naturally increases for larger, less well-understood items.", example: "A well-understood small task might be a 2, while a vague, large feature might be estimated as an imprecise 13 rather than a falsely precise 11 or 12." },
      { order: 8, question: "What is Planning Poker?", answer: "Planning Poker is a consensus-based estimation technique where team members privately select a story point estimate, then reveal them simultaneously. Large differences in estimates prompt discussion, helping surface hidden assumptions before agreeing on a final number.", example: "If one developer estimates a story as 3 and another as 13, the gap usually reveals that one of them knows about a complication the other missed." },
      { order: 9, question: "What does the INVEST acronym describe for user stories?", answer: "INVEST describes qualities of a good user story: Independent, Negotiable, Valuable, Estimable, Small, and Testable. Stories meeting these criteria are easier to plan, estimate, and deliver within a Sprint.", example: "A story that depends entirely on three other unfinished stories fails the \"Independent\" test and is harder to schedule into a Sprint." },
      { order: 10, question: "What are acceptance criteria?", answer: "Acceptance criteria are the specific conditions a user story must satisfy to be considered complete from the customer's perspective. They clarify scope and provide a basis for testing before work is considered Done.", example: "For \"As a user, I want to reset my password,\" acceptance criteria might include: a reset link expires after 1 hour, and the old password stops working immediately." },
      { order: 11, question: "What is the difference between an Epic and a user story?", answer: "An Epic is a large body of work too big to complete in a single Sprint. It is broken down into multiple smaller, independently deliverable user stories that together fulfil the Epic over time.", example: "\"Redesign the onboarding experience\" might be an Epic, broken into stories like \"add a welcome screen,\" \"add a guided tutorial,\" and \"add progress tracking.\"" },
      { order: 12, question: "Why is the Product Backlog described as \"never complete\"?", answer: "The Product Backlog is a living, emergent artifact — it evolves as the product, market, and understanding of customer needs change. It is never considered finished as long as the product itself continues to exist and improve.", example: "Even a mature product's backlog keeps growing as customer feedback, competitor moves, and new opportunities surface new items to consider." },
    ],
    [
      { order: 7, question: "Why do many teams use a Fibonacci-like sequence for story points?", options: ["It is required by the Scrum Guide", "The growing gaps reflect increasing uncertainty for larger items", "It makes estimation exactly precise", "It matches sprint length in days"], correctIndex: 1, explanation: "The widening gaps between numbers avoid false precision for larger, less-understood work." },
      { order: 8, question: "What is Planning Poker used for?", options: ["Ranking team members by skill", "A consensus-based estimation technique that surfaces hidden assumptions", "Selecting the Scrum Master", "Choosing which stories to remove from the backlog"], correctIndex: 1, explanation: "Planning Poker has the team estimate privately and reveal simultaneously, prompting discussion when estimates diverge widely." },
      { order: 9, question: "What does the \"I\" in INVEST stand for?", options: ["Iterative", "Independent", "Intuitive", "Immediate"], correctIndex: 1, explanation: "INVEST stands for Independent, Negotiable, Valuable, Estimable, Small, and Testable." },
      { order: 10, question: "What are acceptance criteria used for?", options: ["Estimating story points", "Defining the specific conditions a story must meet to be considered complete", "Scheduling the Daily Scrum", "Measuring team velocity"], correctIndex: 1, explanation: "Acceptance criteria clarify what \"done\" means for a specific story from the customer's perspective." },
      { order: 11, question: "What is an Epic?", options: ["A synonym for a Sprint Goal", "A large body of work broken down into smaller user stories", "A type of Scrum event", "A performance metric"], correctIndex: 1, explanation: "An Epic is too large for one Sprint and is broken into smaller, independently deliverable stories." },
      { order: 12, question: "Why is the Product Backlog considered \"never complete\"?", options: ["Because it is deleted at the end of every sprint", "Because it is a living artifact that evolves as understanding and needs change", "Because Scrum requires infinite backlogs", "Because only the Scrum Master can close it"], correctIndex: 1, explanation: "The Product Backlog keeps evolving with new insight, feedback, and opportunity for as long as the product exists." },
    ]
  );

  // ── MODULE 6 — Scaling Scrum and Advanced Concepts ───────────────────────
  await expandModule("module-6",
    [
      { order: 7, question: "What is LeSS (Large-Scale Scrum)?", answer: "LeSS is a framework for scaling Scrum to multiple teams working on one product, while staying as close as possible to single-team Scrum rules rather than adding heavy new roles or layers.", example: "Several teams sharing one Product Backlog and one Product Owner, following largely the same Scrum events, is a LeSS-style setup." },
      { order: 8, question: "What is the Nexus framework?", answer: "Nexus, created by Scrum.org, is a framework for scaling Scrum with roughly three to nine teams working from a single Product Backlog. It adds a small integration team and integration events to manage cross-team dependencies and produce one combined Increment.", example: "A Nexus Integration Team specifically checks that the combined work of five teams integrates cleanly before each Sprint Review." },
      { order: 9, question: "Why is a shared Definition of Done important when scaling Scrum across teams?", answer: "When multiple teams contribute to one product, a shared Definition of Done ensures each team's work is held to the same quality bar and can be integrated together reliably — without it, teams' work may be individually \"Done\" but incompatible.", example: "If one team's Definition of Done skips integration testing, their work might break another team's code even though both call their work \"Done.\"" },
      { order: 10, question: "How are cross-team dependencies typically managed at scale?", answer: "Techniques include a Scrum of Scrums for coordination, shared backlogs so dependent work is visible and can be sequenced together, and dependency mapping during joint planning sessions across teams.", example: "Before a quarter starts, several teams jointly map out which features depend on others' work, so sequencing avoids one team blocking another mid-sprint." },
      { order: 11, question: "How does CI/CD (Continuous Integration/Continuous Delivery) relate to Scrum teams?", answer: "CI/CD automates building, testing, and deploying code frequently, which supports Scrum's goal of producing a potentially shippable Increment every Sprint — or even more often. It reduces the manual effort and risk of releasing regularly.", example: "A team with strong CI/CD can deploy a finished feature the same day it's completed, rather than batching changes for a risky end-of-sprint release." },
      { order: 12, question: "How does DevOps relate to Agile and Scrum?", answer: "DevOps extends Agile's collaborative, iterative mindset to include operations — breaking down the wall between building software and running it in production. Scrum teams practicing DevOps often take shared responsibility for reliability and deployment, not just development.", example: "A Scrum team that is also on-call for the features they ship, rather than handing off to a separate operations team, is practicing DevOps." },
    ],
    [
      { order: 7, question: "What is LeSS designed to do?", options: ["Replace the Scrum Master role", "Scale Scrum to multiple teams while staying close to single-team Scrum rules", "Remove the need for a Product Backlog", "Shorten Sprint length"], correctIndex: 1, explanation: "LeSS scales Scrum across multiple teams working on one product without adding heavy new structure." },
      { order: 8, question: "What does the Nexus framework add to support scaling?", options: ["A second Product Owner per team", "A small integration team and integration events", "Longer Sprint timeboxes", "A requirement for daily stakeholder reviews"], correctIndex: 1, explanation: "Nexus adds an integration team and events to manage cross-team dependencies and produce one combined Increment." },
      { order: 9, question: "Why does scaling Scrum require a shared Definition of Done across teams?", options: ["It is optional and rarely used", "To ensure consistent quality so different teams' work integrates reliably", "To reduce the number of Sprint Reviews needed", "Because the Scrum Guide requires identical team sizes"], correctIndex: 1, explanation: "A shared Definition of Done keeps quality consistent so work from multiple teams can be combined without conflict." },
      { order: 10, question: "Which technique helps manage cross-team dependencies at scale?", options: ["Ignoring dependencies until they cause problems", "A Scrum of Scrums and shared backlog visibility", "Assigning one Scrum Master to manage all teams' code", "Removing the Product Owner role"], correctIndex: 1, explanation: "Techniques like a Scrum of Scrums and dependency mapping make cross-team dependencies visible and manageable." },
      { order: 11, question: "How does CI/CD support Scrum's goals?", options: ["It replaces the need for a Sprint Review", "It automates build, test, and deployment, supporting frequent releasable increments", "It eliminates the need for a Definition of Done", "It is unrelated to Scrum"], correctIndex: 1, explanation: "CI/CD reduces the manual effort of releasing often, supporting Scrum's goal of a potentially shippable Increment every Sprint." },
      { order: 12, question: "What does DevOps extend Agile's mindset to include?", options: ["Marketing and sales", "Operations — running software in production, not just building it", "Human resources", "Legal compliance only"], correctIndex: 1, explanation: "DevOps breaks down the separation between development and operations, extending Agile collaboration into running software live." },
    ]
  );

  // ── MODULE 7 — CSM Exam Prep ───────────────────────────────────────────────
  await expandModule("module-7",
    [
      { order: 7, question: "What is a common example of a role violation in Scrum exam scenarios?", answer: "A manager assigning tasks directly to individual Developers, bypassing the team's self-management, is a classic role violation — Scrum expects the Developers to decide internally how to organise their own work.", example: "A scenario describing a manager telling a specific developer which ticket to pick up next is testing whether you recognise this as against Scrum's self-management principle." },
      { order: 8, question: "What is a common example of an event violation in Scrum exam scenarios?", answer: "Cancelling the Sprint Retrospective because \"the team is too busy\" is a common event violation — all five Scrum events are meant to happen every Sprint, and skipping the Retrospective removes the team's chance to improve.", example: "A scenario where a team skips retrospectives for several sprints in a row to \"save time\" is testing whether you recognise this undermines continuous improvement." },
      { order: 9, question: "How does the CSM (Scrum Alliance) compare to the PSM (Scrum.org)?", answer: "CSM (Certified ScrumMaster) is offered by the Scrum Alliance and requires attending an accredited course before the exam. PSM (Professional Scrum Master) is offered by Scrum.org and can be taken independently of any specific course. Both validate Scrum Master knowledge but come from different certifying bodies.", example: "Someone choosing between the two might pick CSM for the structured in-person course experience, or PSM for a self-study, exam-only path." },
      { order: 10, question: "Does a CSM certification need to be renewed?", answer: "Yes — the Scrum Alliance requires CSM holders to renew periodically (historically every two years) by earning Scrum Education Units (SEUs) and paying a renewal fee, keeping the certification current with evolving practice.", example: "A CSM holder attends webinars and conferences over two years to accumulate enough SEUs before their renewal deadline." },
      { order: 11, question: "What is a good study strategy for the Scrum Guide before an exam?", answer: "Read the Scrum Guide multiple times, focusing on understanding why each element exists rather than memorising it word for word — exam questions often test whether you understand the purpose and intent behind a rule, not just its literal text.", example: "Rather than memorising \"Daily Scrum is 15 minutes,\" understand it's there to keep the event focused and give the team a lightweight daily sync — that reasoning helps with scenario questions." },
      { order: 12, question: "Why is \"the Scrum Master is a project manager\" a common misconception?", answer: "A traditional project manager typically plans, assigns, and tracks tasks with authority over the team. A Scrum Master has no such authority — they serve the team as a facilitator and coach, and the team self-manages its own work.", example: "An exam question describing a Scrum Master assigning deadlines to individuals is testing whether you spot that this behaves like a project manager, not a Scrum Master." },
    ],
    [
      { order: 7, question: "A manager assigning tasks directly to individual Developers is an example of what?", options: ["Correct Scrum Master behaviour", "A role violation of the team's self-management", "A required part of Sprint Planning", "The Product Owner's responsibility"], correctIndex: 1, explanation: "Scrum expects Developers to self-manage how they organise their own work — a manager assigning tasks bypasses this." },
      { order: 8, question: "Skipping the Sprint Retrospective to save time is an example of what?", options: ["Good time management", "An event violation that removes the team's chance to improve", "A required Scrum practice", "The Product Owner's decision to make"], correctIndex: 1, explanation: "All five Scrum events, including the Retrospective, are meant to happen every Sprint — skipping it undermines continuous improvement." },
      { order: 9, question: "What is a key difference between CSM and PSM certifications?", options: ["They are identical", "CSM requires an accredited course; PSM can be taken independently as an exam", "PSM is only for developers", "CSM has no exam"], correctIndex: 1, explanation: "CSM (Scrum Alliance) requires attending a course first; PSM (Scrum.org) can be taken as a standalone exam." },
      { order: 10, question: "Does the Certified ScrumMaster credential expire?", options: ["No, it is permanent once earned", "Yes, it requires periodic renewal through SEUs and a fee", "It expires after 6 months", "Only the exam expires, not the certificate"], correctIndex: 1, explanation: "CSM certification requires periodic renewal, historically every two years, via Scrum Education Units and a fee." },
      { order: 11, question: "What is a better exam study approach for the Scrum Guide?", options: ["Memorise it word for word without understanding why", "Understand the purpose behind each rule, not just memorise the text", "Skip it and only study practice questions", "Only read the roles section"], correctIndex: 1, explanation: "Exam questions often test understanding of intent, so grasping why a rule exists helps more than rote memorisation." },
      { order: 12, question: "Why is calling a Scrum Master a \"project manager\" a misconception?", options: ["Because Scrum Masters have more authority than project managers", "Because a Scrum Master has no authority to assign tasks — the team self-manages", "Because project managers don't exist in Agile", "There is no meaningful difference between the two roles"], correctIndex: 1, explanation: "Unlike a traditional project manager, a Scrum Master serves and facilitates rather than directs or assigns work." },
    ]
  );

  console.log("Done — CSM expanded from ~84 to ~168 flashcard+quiz items across 7 modules.");
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
