// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD90GWggrimAFSGgOT8w8KzehQqB5KEk8Y',
    appId: '1:221875967372:web:75ceea1bafd934f2a372a9',
    messagingSenderId: '221875967372',
    projectId: 'binary-6a372',
    authDomain: 'binary-6a372.firebaseapp.com',
    storageBucket: 'binary-6a372.firebasestorage.app',
    measurementId: 'G-RNDTS15MK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFE2pzvqjeN0o-9_bma_dkLKEoC8fU8Ls',
    appId: '1:221875967372:android:2c008d4d146758efa372a9',
    messagingSenderId: '221875967372',
    projectId: 'binary-6a372',
    storageBucket: 'binary-6a372.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKy0i2RAqntvD7Gg8CsdHbP2kkwEkakPI',
    appId: '1:221875967372:ios:bdc09a19b1301dd3a372a9',
    messagingSenderId: '221875967372',
    projectId: 'binary-6a372',
    storageBucket: 'binary-6a372.firebasestorage.app',
    iosBundleId: 'com.example.binary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKy0i2RAqntvD7Gg8CsdHbP2kkwEkakPI',
    appId: '1:221875967372:ios:bdc09a19b1301dd3a372a9',
    messagingSenderId: '221875967372',
    projectId: 'binary-6a372',
    storageBucket: 'binary-6a372.firebasestorage.app',
    iosBundleId: 'com.example.binary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD90GWggrimAFSGgOT8w8KzehQqB5KEk8Y',
    appId: '1:221875967372:web:fe154ac15fadf44ea372a9',
    messagingSenderId: '221875967372',
    projectId: 'binary-6a372',
    authDomain: 'binary-6a372.firebaseapp.com',
    storageBucket: 'binary-6a372.firebasestorage.app',
    measurementId: 'G-62C4727DMS',
  );
}
