// Read public course metadata and free preview lessons through an ephemeral
// guest session. Never writes course or user documents. Deletes its own guest
// identity in finally; tokens are never logged or written to disk.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '../..');
const config = fs.readFileSync(path.join(root, 'lib/firebase_options.dart'), 'utf8');
const web = config.match(/static const FirebaseOptions web = FirebaseOptions\(([\s\S]*?)\);/)[1];
const key = web.match(/apiKey: '([^']+)'/)[1];
const project = web.match(/projectId: '([^']+)'/)[1];
const endpoint = 'https://identitytoolkit.googleapis.com/v1/accounts:';
async function account(action, body) {
  const response = await fetch(endpoint + action + '?key=' + encodeURIComponent(key), {
    method: 'POST', headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body), signal: AbortSignal.timeout(30000),
  });
  const result = await response.json();
  if (!response.ok) throw new Error('Guest ' + action + ': ' + (result.error?.message || response.status));
  return result;
}
function decode(value) {
  if ('stringValue' in value) return value.stringValue;
  if ('integerValue' in value) return Number(value.integerValue);
  if ('doubleValue' in value) return value.doubleValue;
  if ('booleanValue' in value) return value.booleanValue;
  if ('nullValue' in value) return null;
  if ('timestampValue' in value) return value.timestampValue;
  if ('arrayValue' in value) return (value.arrayValue.values || []).map(decode);
  if ('mapValue' in value) return Object.fromEntries(Object.entries(value.mapValue.fields || {}).map(([k,v]) => [k,decode(v)]));
  throw new Error('Unsupported course field type');
}
async function list(collection, token) {
  const url = 'https://firestore.googleapis.com/v1/projects/' + project + '/databases/(default)/documents/' + collection;
  const response = await fetch(url + '?pageSize=100', {
    headers: { Authorization: 'Bearer ' + token }, signal: AbortSignal.timeout(30000),
  });
  const result = await response.json();
  if (!response.ok) throw new Error(collection + ': ' + (result.error?.status || response.status));
  if (result.nextPageToken) throw new Error('Pagination needed: ' + collection);
  return (result.documents || []).map(doc => ({ id: doc.name.split('/').at(-1),
    ...Object.fromEntries(Object.entries(doc.fields || {}).map(([k,v]) => [k,decode(v)])) }));
}
(async () => {
  let token;
  try {
    token = (await account('signUp', { returnSecureToken: true })).idToken;
    const known = [...fs.readFileSync(path.join(root, 'lib/course_catalog.dart'), 'utf8').matchAll(/id: '([^']+)'/g)].map(m => m[1]);
    const courses = (await list('courses', token)).filter(c => known.includes(c.id) && !c.isComingSoon);
    const results = await Promise.allSettled(courses.map(async course => {
      const base = 'courses/' + course.id + '/modules';
      const modules = (await list(base, token)).sort((a,b) => a.order - b.order);
      const free = modules.find(m => m.id === 'module-01' || m.id === 'module-1');
      if (free) {
        for (const kind of ['flashcards', 'quiz']) {
          try {
            free[kind] = (await list(base + '/' + free.id + '/' + kind, token)).sort((a,b) => a.order - b.order);
          } catch (error) {
            free[kind + 'ReadError'] = error.message;
            console.log(error.message);
          }
        }
      }
      return { ...course, modules };
    }));
    const rejected = results.filter(r => r.status === 'rejected');
    if (rejected.length) throw new Error(rejected.map(r => r.reason.message).join('\n'));
    const content = { capturedAt: new Date().toISOString(), source: 'Published Firestore catalogue and free preview content', courses: results.map(r => r.value) };
    const json = JSON.stringify(content, null, 2);
    if (json.includes("'''")) throw new Error('Content contains Dart string delimiter');
    fs.writeFileSync(path.join(__dirname, 'fixture_content.dart'), '// Generated by export_content.js. Contains no account data or credentials.\nconst fixtureContentJson = r\'\'\'' + json + '\'\'\';\n');
    console.log('Read published content for ' + courses.length + ' courses.');
    for (const c of content.courses) console.log(c.id + ': ' + c.modules.length + ' modules');
  } finally {
    if (token) { await account('delete', { idToken: token }); console.log('Temporary guest identity deleted.'); }
  }
})().catch(error => { console.error(error.message); process.exitCode = 1; });
